SYSTEM:
  GPU_ID: "1"
  NUM_WORKERS: 4
  BACKBONE_PATH: "/home/seanyu/research/deep-learning-experiments/cats_and_dogs_playground/experimental_stuff"
  NAME_FLAG: "R50v1_GN_BZ32_Pretrain"
  
TRAIN:
  BATCH_SIZE: 32
  
MODEL:
  OPTIMIZER: "Adam"
  USE_PRETRAIN: True
  NORM_USE: "gn"