SYSTEM:
  NUM_WORKERS: 4
  BACKBONE_PATH: "/home/seanyu/research/deep-learning-experiments/cats_and_dogs_playground/experimental_stuff"
  NAME_FLAG: "R50v2_GNv2_BZ32_noPretrain"
  
TRAIN:
  BATCH_SIZE: 32
  
MODEL:
  OPTIMIZER: "Adam"
  USE_PRETRAIN: False
  BACKBONE: "R-50-v2"
  NORM_USE: "gn_v2"